package sv.edu.udb.entity;
// Generated 13-nov-2019 19:28:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="taller"
)
public class Administrador  implements java.io.Serializable {


     private Integer idadmin;
     private String usuario;
     private String password;

    public Administrador() {
    }

    public Administrador(String usuario, String password) {
       this.usuario = usuario;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idadmin", unique=true, nullable=false)
    public Integer getIdadmin() {
        return this.idadmin;
    }
    
    public void setIdadmin(Integer idadmin) {
        this.idadmin = idadmin;
    }

    
    @Column(name="usuario", nullable=false, length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="password", nullable=false, length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


